### ISSUE TITLE
TypeError: expected string or Unicode object, tuple found

### ISSUE THREAD

**Issue by jimiolaniyan** [votchallenge/toolkit-legacy#219]
I am trying to do a `run_test` with the toolkit but after selecting a sequence it does not give any outputs for a long time (30+ mins). When I kill the process  manually, I keep get the following error:

```
CLIENT: Creating process /usr/bin/python  -c "import sys; sys.path.append('/home/jimiolaniyan/Documents/vot-toolkit/tracker/examples/python');sys.path.append('/home/jimiolaniyan/Documents/vot-toolkit/native/trax/support/python'); import python_ncc"
CLIENT: Working directory is /tmp/oct-ROyAn8
CLIENT: Starting process
CLIENT: Setting up TraX with standard streams connection
@@TRAX:hello "trax.name=" "trax.family=" "trax.image=path;" "trax.region=rectangle;" "trax.description=" "trax.version=2" "trax.channels=color;" 
CLIENT: Tracker process ID: 13753
CLIENT: Connection with tracker established.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jimiolaniyan/Documents/vot-toolkit/tracker/examples/python/python_ncc.py", line 52, in <module>
    image = cv2.imread(imagefile, cv2.IMREAD_GRAYSCALE)
TypeError: expected string or Unicode object, tuple found
@@TRAX:initialize "file:///home/jimiolaniyan/Documents/vot-toolkit/vot/sequences/gymnastics3/color/00000001.jpg" "179.2000,343.2300,57.6500,117.4200" 
@@TRAX:state "179.2000,343.2300,57.6500,117.4200" 
```

Setup:

```
Platform: Linux
Interpreter: Python 2.7
Tracker: ncc
```

**Comment by lukacu** [comment]
See #217 . I am not sure about the timeout though, we will investigate that at some point.

**Comment by lukacu** [comment]
This should be fixed now, please update the toolkit (and trax).
